<a href="https://colab.research.google.com/github/PavelNovikov888/mathematics/blob/master/%D0%92%D1%8B%D1%87%D1%81%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_OLS_%D0%BE%D1%86%D0%B5%D0%BD%D0%BA%D0%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Найти OLS - оценку для коэфф w1, w2  
b^ = ((A^T*A)^-1)*A^T*b

In [3]:
A=np.array([[1,2],[-3,1],[1,2],[1,-1]])
A

array([[ 1,  2],
       [-3,  1],
       [ 1,  2],
       [ 1, -1]])

1.Вычислим матрицу Грама столбцов А

In [5]:
G = A.T@A
G

array([[12,  0],
       [ 0, 10]])

2.Найдем обратную матрицу (A^T*A)^-1

In [7]:
# обратная матрица - все ок
G_inv=np.linalg.inv(G)
print('G inversed:\n',G_inv)

G inversed:
 [[0.08333333 0.        ]
 [0.         0.1       ]]


3.Вычислим A^T*b

In [8]:
b = np.array([1,4,5,0]).T
b_roof = np.dot(A.T,b)
b_roof

array([-6, 16])

4.Вычислим вектор оценок коэффициентов w

In [10]:
w_roof = np.dot(G_inv, b_roof)
w_roof

array([-0.5,  1.6])