<a href="https://colab.research.google.com/github/PavelNovikov888/mathematics/blob/master/%D0%92%D1%8B%D1%87%D1%81%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_OLS_%D0%BE%D1%86%D0%B5%D0%BD%D0%BA%D0%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Найти OLS - оценку для коэфф w1, w2  
b^ = ((A^T*A)^-1)*A^T*b

In [ ]:
A=np.array([[1,2],[-3,1],[1,2],[1,-1]])
A

array([[ 1,  2],
       [-3,  1],
       [ 1,  2],
       [ 1, -1]])

## 1.Вычислим матрицу Грама столбцов А



In [ ]:
G = A.T@A
G

array([[12,  0],
       [ 0, 10]])

## 2.Найдем обратную матрицу (A^T*A)^-1

In [ ]:
# обратная матрица - все ок
G_inv=np.linalg.inv(G)
print('G inversed:\n',G_inv)

G inversed:
 [[0.08333333 0.        ]
 [0.         0.1       ]]


## 3.Вычислим A^T*b

In [ ]:
b = np.array([1,4,5,0]).T
b_roof = np.dot(A.T,b)
b_roof

array([-6, 16])

## 4.Вычислим вектор оценок коэффициентов w

In [ ]:
w_roof = np.dot(G_inv, b_roof)
w_roof

array([-0.5,  1.6])

# Коллинеарность

In [ ]:
# коллинеарность
A1=np.array([5,1,2]).T
A2=np.array([4,2,8]).T
np.corrcoef(A1,A2)

array([[1.        , 0.05241424],
       [0.05241424, 1.        ]])

In [ ]:
v = np.array([5, 1, 2])
u = np.array([4, 2, 8])
print('{:.2f}'.format(np.corrcoef(u, v)[0][1]))

In [ ]:
x_1 = np.array([5.1, 1.8, 2.1, 10.3, 12.1, 12.6])
x_2 = np.array([10.2, 3.7, 4.1, 20.5, 24.2, 24.1])
x_3 = np.array([2.5, 0.9, 1.1, 5.1, 6.1, 6.3])
A = np.array([x_1,x_2,x_3])

In [ ]:
d=np.corrcoef(A)
d

array([[1.        , 0.99925473, 0.99983661],
       [0.99925473, 1.        , 0.99906626],
       [0.99983661, 0.99906626, 1.        ]])

In [ ]:
print('rk(d):\n',np.linalg.matrix_rank(d))

rk(d):
 3


In [ ]:
print('det(A1)):\n',round(np.linalg.det(d),7))

det(A1)):
 5e-07
