<a href="https://colab.research.google.com/github/PavelNovikov888/mathematics/blob/master/%D0%9E%D0%BF%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D0%B8_%D1%81_%D0%BC%D0%B0%D1%82%D1%80%D0%B8%D1%86%D0%B0%D0%BC%D0%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Как создать матрицу?

## как двумерный массив Numpy

In [2]:
# как двумерный массив Numpy
np.array( [ [1,1] , [2,3] , [4,5] ] )

array([[1, 1],
       [2, 3],
       [4, 5]])

## преобразовать из Pandas DataFrame

In [3]:
# преобразовать из Pandas DataFrame
import pandas as pd

data=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
df = pd.DataFrame(data)

A = df.values

print('Data Frame:')
print(df)
print('Matrix:')
print(A)

Data Frame:
    0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
Matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## размер матрицы

In [4]:
# размер матрицы
np.shape(A)

(4, 3)

## вектор-столбец

In [5]:
# вектор-столбец
x=np.array([1,2,3])
np.reshape(x,(3,1))

array([[1],
       [2],
       [3]])

## вектор-строка

In [6]:
# вектор-строка
np.reshape(x,(1,3))

array([[1, 2, 3]])

In [7]:
# вектор-строка
x_row=np.array([1, 2, 3], ndmin=2)
print(x_row,np.shape(x_row))

[[1 2 3]] (1, 3)


# Индексация матриц (двумерных массивов numpy)

In [8]:
# индексация матриц (двумерных массивов numpy)
print('матрица А:')
print(A)
print('Первая строка матрицы А:')
print(A[0])
print('Третий столбец матрицы А:')
print(A[:,2])
print('Элемент а_43:')
print(A[3,2])

матрица А:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Первая строка матрицы А:
[1 2 3]
Третий столбец матрицы А:
[ 3  6  9 12]
Элемент а_43:
12


# Создание специальных матриц

## нулевая

In [10]:
# нулевая
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

## единичная

In [11]:
# единичная
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## матрица единиц

In [12]:
# матрица единиц
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## диагональная матрица

In [13]:
# Диагональная
diagonal=[1,2,3]
np.diag(diagonal)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

## шаровая

In [14]:
# Шаровая
5*np.eye(3)

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

# Операции с матрицами

In [15]:
A=np.array([[1,1],[2,3],[4,5]])
B=np.array([[1,-1],[-2,3],[4,-5]])

In [16]:
A

array([[1, 1],
       [2, 3],
       [4, 5]])

In [17]:
B

array([[ 1, -1],
       [-2,  3],
       [ 4, -5]])

## +, -, *, .T

In [18]:
A+B

array([[2, 0],
       [0, 6],
       [8, 0]])

In [19]:
B+A

array([[2, 0],
       [0, 6],
       [8, 0]])

In [20]:
A-B

array([[ 0,  2],
       [ 4,  0],
       [ 0, 10]])

In [21]:
2*A

array([[ 2,  2],
       [ 4,  6],
       [ 8, 10]])

In [22]:
A.T

array([[1, 2, 4],
       [1, 3, 5]])

# Транспонирование вектора

In [23]:
# как транспонировать вектор?
x=np.array([1,2,3])
x.T

array([1, 2, 3])

In [24]:
x_col=np.reshape(x,(3,1))
print(x_col)
print(np.shape(x_col))

[[1]
 [2]
 [3]]
(3, 1)


In [25]:
x_col.T

array([[1, 2, 3]])

In [26]:
print(np.shape(x))
print(np.shape(x_col))
print(np.shape(x_col.T))

(3,)
(3, 1)
(1, 3)


# Практика


Данные по доходам и расходам каждого члена семьи Ивановых записаны в одномерные массивы numpy:

In [27]:
import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

Составьте матрицу Inc доходов семьи, расположив доходы мужа, жены и тёщи в первый, второй и третий столбцы матрицы.

In [28]:
Inc = np.zeros((3,3))
Inc


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
Inc[0] = Husband_Income
Inc[1] = Wife_Income
Inc[2] = Mother_In_Law_Income
Inc

array([[100., 220., 140.],
       [150., 200., 130.],
       [ 90.,  80., 100.]])

In [30]:
IncT = Inc.T
IncT

array([[100., 150.,  90.],
       [220., 200.,  80.],
       [140., 130., 100.]])

Составьте матрицу Cons расходов семьи, расположив расходы мужа, жены и тёщи в первый, второй и третий столбцы.

In [31]:
Cons = np.zeros((3,3))
Cons[0] = Husband_Consumption
Cons[1] = Wife_Consumption
Cons[2] = Mother_In_Law_Consumption
Cons.T

array([[ 50., 100., 100.],
       [ 50.,  80.,  20.],
       [ 60., 140., 140.]])

Доходы представлены до уплаты налогов. Налоговая ставка — 13 %. Вычислите матрицу доходов семьи Ивановых после уплаты налогов.

In [32]:
IncT_13 = IncT*0.87

In [33]:
IncT_13

array([[ 87. , 130.5,  78.3],
       [191.4, 174. ,  69.6],
       [121.8, 113.1,  87. ]])

Вычислите матрицу T , которая покажет баланс семьи Ивановых за один месяц (то есть разницу между доходами после вычета налога и расходами).

In [34]:
T = IncT_13 - Cons.T
T

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])