<a href="https://colab.research.google.com/github/PavelNovikov888/mathematics/blob/master/%D0%9E%D0%BF%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D0%B8_%D1%81__%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B0%D0%BC%D0%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Создать вектор

## как одномерный массив numpy

In [ ]:
a=np.array([1,2,3])
print(a, type(a))

[1 2 3] <class 'numpy.ndarray'>


In [ ]:
np.array([1,2,3], dtype='float')

array([1., 2., 3.])

## преобразовать из списка (list)

In [ ]:
x=[1,2,3]
x_arr=np.array(x)
print(x, type(x))
print(x_arr, type(x_arr))

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


## нулевой вектор

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

## вектор из единиц

In [ ]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

## массив чисел по порядку

In [ ]:
np.arange(10,50, 5)

array([10, 15, 20, 25, 30, 35, 40, 45])

## случайный вектор

In [ ]:
np.random.randint(-4, 2, 10) # dim=10, случаные целые числа от -4 до 2

array([ 1, -4, -2, -3, -4,  1, -4, -3, -4, -1])

## преобразовать из Pandas Series

In [ ]:
import pandas as pd
data = [65, 70, 120, 35]
s = pd.Series(data)
print('Series:\n',s)

Series:
 0     65
1     70
2    120
3     35
dtype: int64


In [ ]:
x = s.values # возвращает значения s
print('vector:\n',x)
print('type of x:',type(x))

vector:
 [ 65  70 120  35]
type of x: <class 'numpy.ndarray'>


## преобразовать из Pandas DataFrame

In [ ]:
d = {'$$': [65, 70, 120, 35], '2.Area': [50, 52, 80, 33],'3.Rooms':[3,2,1,1],
     '4.Floor':[5,12,10,3], '5.Demo':[8,4,5,10]}
df = pd.DataFrame(d)
print('Data Frame:\n',df)

Data Frame:
     $$  2.Area  3.Rooms  4.Floor  5.Demo
0   65      50        3        5       8
1   70      52        2       12       4
2  120      80        1       10       5
3   35      33        1        3      10


In [ ]:
A = df.values # возвращает значения df
print('Matrix:\n',A)

Matrix:
 [[ 65  50   3   5   8]
 [ 70  52   2  12   4]
 [120  80   1  10   5]
 [ 35  33   1   3  10]]


# Срез матрицы

In [ ]:
x=A[1] # вторая строка матрицы А
print('Second apartment vector:\n',x)
print('type of x:',type(x))

Second apartment vector:
 [70 52  2 12  4]
type of x: <class 'numpy.ndarray'>


In [ ]:
y=A[:,0] # первый столбец матрицы А
print('$$ vector:\n',y)

$$ vector:
 [ 65  70 120  35]


In [ ]:
# индексация векторов - поиск нужной координаты
print('$$ of 3 apartment:',y[2]) # третья координата

$$ of 3 apartment: 120


# Размерность вектора

In [ ]:

print('Number of apartments = dim(y):', len(y))

Number of apartments = dim(y): 4


# Операции с векторами

## сумма и произведение векторов

In [ ]:
# сумма векторов и умножение на число
a=np.array([1,2,3])
b=np.array([6,7,8])
print('a+b:',a+b)
print('2a:',2*a)

a+b: [ 7  9 11]
2a: [2 4 6]


In [ ]:
# сумма списков и умножение на число не является векторной операцией!
a_list=[1,2,3]
b_list=[6,7,8]
print('a+b:',a_list+b_list)
print('2a:',2*a_list)

a+b: [1, 2, 3, 6, 7, 8]
2a: [1, 2, 3, 1, 2, 3]


## линейная комбинация

In [ ]:
# линейная комбинация с коэффициентами 2, 2, 3
a=np.array([1,2,3])
b=np.array([6,7,8])
c=np.array([1,0,1])

d=2*a+2*b+3*c
print('linear combination:',d)

linear combination: [17 18 25]


## скалярное произведение

In [ ]:
# скалярное произведение

s=np.dot(a,b)
print('scalar product:',s)

# покоординатное умножение
print('coordinate product:',a*b)

scalar product: 44
coordinate product: [ 6 14 24]


In [ ]:
# скалярное произведение - еще один способ
s1=a@b
print('scalar product:',s1)

scalar product: 44


## длина вектора

In [ ]:
# длина вектора
l=np.linalg.norm(a)
print('length of a:',l)

length of a: 3.7416573867739413


## нормировка

In [ ]:
# нормировка
a_norm=a/np.linalg.norm(a)
print('a_norm:',a_norm)
print('length of a_norm:',np.linalg.norm(a_norm))

a_norm: [0.26726124 0.53452248 0.80178373]
length of a_norm: 1.0


## пропорциональность и ортогональность

In [ ]:
#пропорциональность и ортогональность
a=np.array([1,2,1])
b=a*2
c=np.array([-1,1,-1])
print('a:',a)
print('b:',b)
print('c:',c)

a: [1 2 1]
b: [2 4 2]
c: [-1  1 -1]


In [ ]:
#пропорциональность и ортогональность
print("(a,b):",np.dot(a,b))
print("(a,c):",np.dot(a,c))
print("(b,c):",np.dot(b,c))

(a,b): 12
(a,c): 0
(b,c): 0


In [ ]:
# попарная ортогональность - да
a=np.array([1,0,1])
b=np.array([0,1,0])
c=np.array([1,0,-1])
print('a:',a)
print('b:',b)
print('c:',c)

a: [1 0 1]
b: [0 1 0]
c: [ 1  0 -1]


In [ ]:
# попарная ортогональность - да
print('(a,b):',np.dot(a,b))
print('(b,c):',np.dot(b,c))
print('(a,c):',np.dot(a,c))

(a,b): 0
(b,c): 0
(a,c): 0


In [ ]:
# попарная ортогональность - нет
c1=np.array([1,0,4])
print('a:',a)
print('b:',b)
print('с1:',c1)

a: [1 0 1]
b: [0 1 0]
с1: [1 0 4]


In [ ]:
# попарная ортогональность - нет
print('(a,b):',a@b)
print('(b,c1):',b@c1)
print('(a,c1):',a@c1)

(a,b): 0
(b,c1): 0
(a,c1): 5


In [ ]:
# Практика
В Hut_Paradise_DF представлен фрагмент базы данных агентства «Рай в Шалаше». По строкам расположены квартиры, по столбцам — параметры: арендная плата, общая площадь, количество комнат, этаж, количество показов на две недели и жилая площадь:

In [ ]:
import pandas as pd

Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85],
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65],
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5],
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10],
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})

In [ ]:
Hut_Paradise_DF

1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area
0      65      50        3        5                 8          37
1      70      52        2       12                 4          40
2     120      80        1       10                 5          65
3      35      33        1        3                10          20
4      40      33        1        6                20          16
5      50      44        2       13                12          35
6     100      80        4        8                 5          60
7      90      65        3       21                 1          50
8      85      65        2        5                10          40

Найдите вектор параметров квартиры номер 5 (нумерация квартир — с 1). Для преобразования DataFrame в массив numpy можно воспользоваться атрибутом values:

In [ ]:
Hut_Paradise_values = Hut_Paradise_DF.values

In [ ]:
Hut_Paradise_values[4]

array([40, 33,  1,  6, 20, 16])

In [ ]:
#Найдите вектор этажей всех квартир
Hut_Paradise_values[:,3]

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5])

In [ ]:
#Вычислите вектор нежилой площади
Notlive = Hut_Paradise_values[:,1]-Hut_Paradise_values[:,-1]
Notlive

array([13, 12, 15, 13, 17,  9, 20, 15, 25])

Пусть в первой квартире один просмотр занимает 10 минут, во второй — 20 минут, в третьей — полчаса, в четверой — 15 минут, в пятой — 5 минут, в шестой — 40 минут, в седьмой — 20 минут, в восьмой — 8 минут и в девятой — 20 минут.

Найдите продолжительность просмотров в минутах во всех квартирах за две недели.

In [ ]:
list_of_seen = [10,20,30,15,5,40,20,8,20]
list_of_seen_m = np.array(list_of_seen)
time_of_seen = Hut_Paradise_values[:,4]@list_of_seen_m
print(time_of_seen)

1348


Дано три вектора. Составьте линейную комбинацию векторов v и w с коэффициентами 2 и -3. Выберите координаты полученного вектора:

In [ ]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

In [ ]:
a  = v*2 + w*(-3)
a

array([-3, 14,  3,  4,  2])

In [ ]:
print('(a,u):',a@u)

(a,u): 0
