<a href="https://colab.research.google.com/github/PavelNovikov888/mathematics/blob/master/%D0%9F%D1%80%D0%BE%D0%B8%D0%B7%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5_%D0%BC%D0%B0%D1%82%D1%80%D0%B8%D1%86.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Произведение матриц

In [2]:
# произведение матриц
A=np.random.randint(5, 12, (3,3))
B=np.random.randint(-2, 4, (3,3))

In [3]:
A

array([[ 7,  6, 11],
       [ 5,  8, 10],
       [ 7,  9,  8]])

In [4]:
B

array([[-2,  2, -2],
       [ 0,  3, -1],
       [-1,  3,  1]])

## Поэлементное умножение

In [5]:
# Поэлементное умножение
A*B

array([[-14,  12, -22],
       [  0,  24, -10],
       [ -7,  27,   8]])

## Тип np.matrix

In [6]:
# тип np.matrix
A_m=np.matrix(A)
B_m=np.matrix(B)
print(A_m*B_m)

[[-25  65  -9]
 [-20  64  -8]
 [-22  65 -15]]


## Матричное умножение

In [7]:
# Матричное умножение
np.dot(A,B)

array([[-25,  65,  -9],
       [-20,  64,  -8],
       [-22,  65, -15]])

In [8]:
# Матричное умножение
A@B

array([[-25,  65,  -9],
       [-20,  64,  -8],
       [-22,  65, -15]])

## Правила умножения и прмимеры

In [9]:
# Порядок умножения AB != BA
B@A

array([[-18, -14, -18],
       [  8,  15,  22],
       [ 15,  27,  27]])

In [10]:
# Умножение прямоугольных матриц возможно не в любом порядке
A=np.random.randint(5, 12, (3,5))
B=np.random.randint(-2, 4, (5,2))
print('A:\n',A)
print('B:\n',B)

A:
 [[ 5  9  7  8  6]
 [ 5  9 11  7 10]
 [11  8  8  6 11]]
B:
 [[-2  3]
 [ 2 -1]
 [ 1 -2]
 [-2 -1]
 [-2  0]]


In [11]:
# Умножение прямоугольных матриц возможно не в любом порядке
A@B

array([[-13, -16],
       [-15, -23],
       [-32,   3]])

In [12]:
# Умножение прямоугольных матриц возможно не в любом порядке
B@A

ValueError: ignored

# Размер произведения матриц

In [13]:
# размер произведения матриц
print('shape of A:', np.shape(A))
print('shape of B:', np.shape(B))
print('shape of AB:', np.shape(A@B))

shape of A: (3, 5)
shape of B: (5, 2)
shape of AB: (3, 2)


# Умножение на специальные матрицы

In [14]:
# умножение на специальные матрицы
A=np.random.randint(-4, 4, (4,4))
D=np.diag([1,2,0,-1])
print('A:\n',A)
print('D:\n',D)
print('AD:\n',A@D)
print('DA:\n',D@A)

A:
 [[-1 -4 -3  3]
 [-3  2 -1  2]
 [ 0 -1  2  3]
 [-2  3  2  0]]
D:
 [[ 1  0  0  0]
 [ 0  2  0  0]
 [ 0  0  0  0]
 [ 0  0  0 -1]]
AD:
 [[-1 -8  0 -3]
 [-3  4  0 -2]
 [ 0 -2  0 -3]
 [-2  6  0  0]]
DA:
 [[-1 -4 -3  3]
 [-6  4 -2  4]
 [ 0  0  0  0]
 [ 2 -3 -2  0]]


## Умножение на одномерный массив numpy

In [15]:
# умножение на одномерный массив numpy
A=np.array([[1,0,1],[1,1,1]])
b=np.array([-3,4,5])
A@b

array([2, 6])

In [16]:
b@A

ValueError: ignored

# Матрица Грама

In [17]:
# матрица Грама ортогональной системы векторов
x=np.array([1,1,1])
y=np.array([1,0,-1])
z=np.array([-1,2,-1])
A=np.array([x,y,z])
print (A, type(A))

[[ 1  1  1]
 [ 1  0 -1]
 [-1  2 -1]] <class 'numpy.ndarray'>


In [18]:
# матрица Грама ортогональной системы векторов
A@A.T

array([[3, 0, 0],
       [0, 2, 0],
       [0, 0, 6]])

In [19]:
# матрица Грама ортонормированной системы векторов
x_norm=x/np.linalg.norm(x)
y_norm=y/np.linalg.norm(y)
z_norm=z/np.linalg.norm(z)
A_norm=np.array([x_norm,y_norm,z_norm])
print (A_norm, type(A_norm))

[[ 0.57735027  0.57735027  0.57735027]
 [ 0.70710678  0.         -0.70710678]
 [-0.40824829  0.81649658 -0.40824829]] <class 'numpy.ndarray'>


In [20]:
# матрица Грама ортонормированной системы векторов
A_norm@A_norm.T

array([[ 1.00000000e+00, -1.77961928e-17,  1.66584120e-17],
       [-1.77961928e-17,  1.00000000e+00, -2.45142679e-17],
       [ 1.66584120e-17, -2.45142679e-17,  1.00000000e+00]])

In [21]:
# ортонормированные системы рулят! :)
np.round(A_norm@A_norm.T,1)

array([[ 1., -0.,  0.],
       [-0.,  1., -0.],
       [ 0., -0.,  1.]])